# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Pipeline
on:
  push:
    branches: ["main", "ci-pipeline"]
  pull_request:
    branches: ["Skeleton", "ci-pipeline"]   

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: start containers
        run: docker-compose up -detach

      # use this step to give time for containers to start
      - name: wait for containers to be ready
        run: sleep 5s
        shell: bash

      - name: run migrations
        run: docker-compose exec -t api npm run db-migrations:up

      - name: run tests on the api
        run: docker-compose exec -t api npm test

      - name: run tests on the client
        run: docker-compose exec -t client npm test
